-- Generated by matugen — do not edit
-- Loaded via dofile() from hyprland.lua on startup and after wallpaper change
hl.config({
    general = {
        col = {
            active_border   = "rgba({{colors.primary.default.hex_stripped}}ee)",
            inactive_border = "rgba({{colors.surface_variant.default.hex_stripped}}aa)",
        }
    }
})
