// Generated by matugen — do not edit
pragma Singleton

import QtQuick
import Quickshell

Singleton {
    readonly property color bg: "{{colors.surface.default.hex}}"
    readonly property color fg: "{{colors.on_surface.default.hex}}"
    readonly property color accent: "{{colors.primary.default.hex}}"
    readonly property color accentText: "{{colors.on_primary.default.hex}}"
    readonly property color dim: "{{colors.on_surface_variant.default.hex}}"
    readonly property color urgent: "{{colors.error.default.hex}}"
}
