// Generated by matugen — do not edit
pragma Singleton

import QtQuick
import Quickshell

Singleton {
    readonly property color bg: "#181115"
    readonly property color fg: "#eddfe4"
    readonly property color accent: "#f8b1dd"
    readonly property color accentText: "#4f1e42"
    readonly property color dim: "#d3c2ca"
    readonly property color urgent: "#ffb4ab"
}
