-- ~/.config/hypr/hyprland.lua
-- Hyprland 0.55+ — Lua config entry point
require("monitors")
require("autostart")
require("settings")
require("curves")
require("animations")
require("keybinds")
require("window-rules")

-- Dynamic border colors — generated by matugen, reloaded on wallpaper change
local config = os.getenv("XDG_CONFIG_HOME") or os.getenv("HOME") .. "/.config"
dofile(config .. "/hypr/hyprland-colors.lua")
