-- ~/.config/hypr/hyprland.lua
-- Hyprland 0.55+ — Lua config entry point
require("monitors")
require("autostart")
require("environment")
require("settings")
require("curves")
require("animations")
require("keybinds")
require("window-rules")

-- Dynamic border colors — generated by matugen, reloaded on wallpaper change
dofile(os.getenv("HOME") .. "/.config/hypr/hyprland-colors.lua")
