-- Generated by matugen — do not edit
-- Loaded via dofile() from hyprland.lua on startup and after wallpaper change
hl.config({
    general = {
        col = {
            active_border   = "rgba(82d3e0ee)",
            inactive_border = "rgba(3f484aaa)",
        }
    }
})
