-- Generated by matugen — do not edit
-- Loaded via dofile() from hyprland.lua on startup and after wallpaper change
hl.config({
    general = {
        col = {
            active_border   = "rgba(ffb4a5ee)",
            inactive_border = "rgba(534340aa)",
        }
    }
})
