// Generated by matugen — do not edit
pragma Singleton

import QtQuick
import Quickshell

Singleton {
    readonly property color bg: "#141318"
    readonly property color fg: "#e6e1e9"
    readonly property color accent: "#cbbeff"
    readonly property color dim: "#c9c4cf"
    readonly property color urgent: "#ffb4ab"
}
