// Generated by matugen — do not edit
pragma Singleton

import QtQuick
import Quickshell

Singleton {
    readonly property color bg: "#111318"
    readonly property color fg: "#e2e2e9"
    readonly property color accent: "#adc6ff"
    readonly property color accentText: "#102f60"
    readonly property color dim: "#c4c6d0"
    readonly property color urgent: "#ffb4ab"
}
